{% set name = "conda-devenv" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ESSS/conda-devenv.git
  git_rev: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - conda-devenv = conda_devenv.devenv:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - jinja2
    - pyyaml

test:
  imports:
    - conda_devenv
  commands:
    - conda-devenv --help

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A tool to work with multiple projects in develop-mode using conda-env.'
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
