{% set name = "conda-devenv" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/conda-devenv/archive/{{ version }}.tar.gz
  sha256: a0a88f7d482ec6293aee52a3026055e32a8719ec828f0496fc9b5c084c7ab33f

build:
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - python -m pip install . --no-deps --ignore-installed
  entry_points:
    - conda-devenv = conda_devenv.devenv:main
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools_scm
  run:
    - conda  >=4.3
    - python
    - jinja2
    - pyyaml
    - six

test:
  requires:
    - pytest >=3
    - pytest-datadir >=1.0
    - pytest-mock
  imports:
    - conda_devenv
  commands:
    - conda-devenv --version
    - conda-devenv --help
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A tool to work with multiple projects in develop-mode using conda-env.'
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
    - prusse-martin
    - oliveira-esss
