travis:
  secure:
    BINSTAR_TOKEN: rIKdwB+w6K2Wx3g2e1f+uZsNNTwY3ymlB77VU6wxKNQVlrqFz6KU2W6mFoXn9Y186OWMoMLWsOsklWQ45X3nCqJnwl1/HUH+tA1fh92nhJb5evc8mIW/ZPbJD1SmOr78xLqVAsuAAZNMJn96Gd488Eif/k3hWgXnqaDueGJb2/uE+YlPdRoHYdEIte7VpPdw5kfDNrO1ZBpyxztAD+fqu8T0TxbjN1yco4HQjWJ6VE5GGvHnP3WJRRwh07UQ9x1scAJhHgCaWYK+maepWBdtwdqK2qshWSXMWNOzyCWG4eSTuYvPCcWBTULQA/p9/uFoJOXlYiye5riKBk4uEBKHawbQoSy86hqS0q6slRURl/LAsLw2nwBXFsO1KShyRmhQI8DzqYq8xuWR1bt+rmAncY++8aHpql6a+sNd/btqRQt/Pk0g0DV3GAH5pcEbtmVRYZHKg/E8+7nY1rB8lQZioH8Hw1YQmOYGmn41X7VOiCKe7x6DtJcSO9a0T2OmHhBMeH7NQ1ndCdKDw62RN1Vpw9khEdo6RK2Gpd+IkzLHoLNFVGBq4eQKquQoPN88eBoSJJ2AqKNvpdHavs6ageLT9ybcA4KAzt2OHshgsP4Ylr1YlPrAXUXdwBbsgBKAoycWRZKqjKVuy58Yc5+KZo/PECoruElpyDj0Ku843cnoeiU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
